### ISSUE TITLE
Cannot compile with zig 0.15.1

### ISSUE THREAD

**Issue by Logickin-Lambda** [zig-gamedev/zgpu#19]
During waiting for the zgui pull request that including the zig 0.15.1 update, I decided to spend some time for checking if there are other libraries can't build with the latest version.

Since I am currently use zgui + zgpu + zglfw + zaudio a lot for some learning projects and I expect to use them a lot in the near future, I decided to check if these libraries can be compiled properly. I have found that zgpu can't compile with zig 0.15.1, so I attempted to update the library; however, seems like I have came across a part of the code I am not familiar with:

``` zig
usingnamespace if (emscripten) struct {
    // Missing symbols
    var wgpuDeviceTickWarnPrinted: bool = false;
    pub export fn wgpuDeviceTick() void {
        if (!wgpuDeviceTickWarnPrinted) {
            std.log.warn("wgpuDeviceTick(): this fn should be avoided! RequestAnimationFrame() is advised for smooth rendering in browser.", .{});
            wgpuDeviceTickWarnPrinted = true;
        }
        emscripten_sleep(1);
    }
} else struct {};
```

Because of the recent update to the usingnamespace, it throws this error:

``` zig
src\zgpu.zig:1858:16: error: expected ',' after field
usingnamespace if (emscripten) struct {
```

However, I am not familiar with `usingnamespace`, neither I work on emscripten projects, so I am not sure what is the intended compilation results and behavior of the emscripten application. Anyone have some ideas with it?

**Comment by Logickin-Lambda** [comment]
The update is done, but because of the issue of [outdated dawn library](https://github.com/zig-gamedev/zgui/pull/51#issuecomment-3240292543) mentioned in zgui, while I have figured out how to compile the [dawn project ](https://github.com/google/dawn) (but with cmake and ninja, not with build.zig), let me see if I can do something to update zgui such that it stay relevant to the newer dawn version.

Perhaps this will help for the recent imgui update for zgui, but because of the complexity of dawn, this might not be something can be figured out in the near future.
